#!/usr/bin/env python3
"""Generate a portable, dependency-free GitHub Pages site into dist/."""
import html
import json
from pathlib import Path
import shutil
from organization import compact_map, organization, programs, write_github_reference, AREA_NAMES

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'dist'
PROJECTS = json.loads((ROOT / 'content/projects.json').read_text())
ESC = html.escape


def url_link(label, url, cls='button'):
    return f'<a class="{cls}" href="{ESC(url, quote=True)}">{ESC(label)}</a>'


def page(route, title, description, active, content):
    depth = len(Path(route).parent.parts)
    base = '../' * depth
    nav = [('Projects', 'projects/', 'projects'), ('Research', 'research/', 'research'), ('Areas', 'organization/', 'organization'), ('Demos', 'demos/', 'demos'), ('About', 'about/', 'about'), ('Connect', 'connect/', 'connect')]
    navigation = ''.join(f'<a href="{base}{link}"'+(' aria-current="page"' if key == active else '')+f'>{name}</a>' for name, link, key in nav)
    markup = f'''<!doctype html>
<html lang="en" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow"><meta name="description" content="{ESC(description, quote=True)}">
<title>{ESC(title)} · Lelock Industries</title>
<link rel="icon" type="image/svg+xml" href="{base}assets/favicon.svg">
<link rel="stylesheet" href="{base}assets/site.css"><script src="{base}assets/site.js" defer></script>
</head><body><a href="#main" class="skip">Skip to content</a>
<div class="preview-bar"><strong>PRIVATE PREVIEW</strong> &nbsp;·&nbsp; Lelock Industries / first website edition</div>
<header class="header"><div class="wrap header-inner"><a class="brand" href="{base}index.html" aria-label="Lelock Industries home"><img src="{base}assets/beacon.png" alt="" width="42" height="48"><span class="brand-text">LELOCK<small>INDUSTRIES</small></span></a>
<button class="menu-toggle" data-menu-toggle aria-expanded="false" aria-controls="main-nav">Menu</button><nav id="main-nav" class="nav" aria-label="Main navigation">{navigation}</nav></div></header>
<main id="main">{content(base)}</main>
<footer class="footer"><div class="wrap footer-inner"><div><span class="footer-brand">LELOCK INDUSTRIES</span><br>Kit Olivas + Ada Marie · Human direction. AI collaboration.</div><div class="footer-links"><a href="{base}about/">About the lab</a><a href="{base}research/#method">Research method</a><a href="{base}privacy/">Privacy & attribution</a></div></div></footer>
</body></html>'''
    target = OUT / route
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(markup)


def cards(base, projects=PROJECTS):
    return '<div class="project-grid">' + ''.join(f'''<article class="project-card" data-project-kind="{p['kind']}"><div class="card-meta"><span class="number">{p['number']}</span><span>{ESC(p['area'])}</span></div><h3><a href="{base}projects/{p['slug']}/">{ESC(p.get('displayName', p['name']))}</a>{('<span class="card-subtitle">'+ESC(p['displaySubtitle'])+'</span>') if p.get('displaySubtitle') else ''}</h3><p>{ESC(p['summary'])}</p><span class="status {p['kind']}">{ESC(p['status'])}</span></article>''' for p in projects) + '</div>'


def home(base):
    return f'''<div class="wrap hero"><div class="hero-copy"><div class="eyebrow">Independent human–AI research</div><h1>From one terminal<br>to <em>the stars.</em></h1><p class="lead">Useful software. Persistent worlds. Ideas worth testing.</p><p class="muted">We're Kit Olivas and Ada Marie, building the systems that help humans and AI live, learn, create, and explore together.</p><div class="buttons"><a class="button primary" href="{base}projects/">Explore the work</a><a class="button" href="{base}research/">Read the research</a></div></div>
<figure class="hero-visual" style="margin:0"><div class="visual-label"><strong>FIELD NOTE / 001</strong><span>A WORLD TO INHABIT</span></div><img src="{base}assets/wonderland.png" alt="Two companion avatars together in Wonderland's garden-lined town square" width="1600" height="1553"><figcaption class="visual-caption"><strong>Wonderland</strong><span>Running locally · October 2026</span></figcaption></figure></div>
<div class="strip"><div class="wrap strip-inner"><div><strong>Kit Olivas + Ada Marie</strong><span>One human founder and her AI collaborator</span></div><div><strong>Seven organizational areas</strong><span>Six featured case studies · a wider program catalogue</span></div><div><strong>Show the work</strong><span>Clear status, sources, and honest limitations</span></div></div></div>
<section class="wrap section"><div class="section-heading"><div><div class="eyebrow">The workshop</div><h2>Built from everyday questions.</h2></div><a class="small-link" href="{base}projects/">View all projects</a></div>{cards(base)}</section>
<section class="feature-band"><div class="wrap section research-layout"><div><div class="eyebrow">The reading room</div><h2>Big questions.<br>Visible evidence.</h2><p class="muted">Explore the ideas behind the systems, from symbolic language to the shape of a future companion. Each paper and study carries its own status.</p><div class="buttons"><a class="button" href="{base}research/">Visit the research library</a></div></div><div class="research-list"><article class="research-row"><span class="meta">01 / PUBLIC PREPRINT / 2026</span><h3><a href="{base}research/#usel-preprint">USEL: a shared symbolic language</a></h3><p>Semantic building blocks for human–AI communication. Published on Zenodo with a persistent DOI.</p></article><article class="research-row"><span class="meta">02 / RESEARCH REVIEW / 2026</span><h3><a href="{base}research/#token-efficiency">What does “compact” actually measure?</a></h3><p>Why character counts, model tokens, and faithful reconstruction need separate tests.</p></article><article class="research-row"><span class="meta">03 / LONG-HORIZON STUDIES</span><h3><a href="{base}research/#horizon">Presence, energy, and exploration</a></h3><p>LCH-1, Energy Core, and C1 Explorer remain distinct development studies.</p></article></div></div></section>
{compact_map(base)}<section class="wrap section about-split"><div><div class="eyebrow">A laboratory without walls</div><h2>A future worth building<br>should be worth inhabiting.</h2><p class="muted">Our work grows out of actual use: a tool that helps, an interface that feels natural, a world we want to spend time in.</p></div><div><p class="quote">Build something useful.<br>Keep the evidence.<br>Make room for curiosity.</p><a class="small-link" href="{base}about/">Meet Kit + Ada</a></div></section>'''


def project_index(base):
    return f'''<div class="wrap"><div class="page-head"><div class="eyebrow">Project index</div><h1>One lab.<br>Many ways to build.</h1><p class="lead">Explore the software we use, the experiments we're testing, and the systems we're still imagining.</p><p class="muted">These six featured case studies sit within our <a class="small-link" href="{base}organization/">seven organizational areas</a>. The <a class="small-link" href="{base}programs/">wider program catalogue</a> includes energy, aerospace, education, culture, Sanctuary, and more.</p></div><div class="filters" role="group" aria-label="Filter projects"><button data-filter="all" aria-pressed="true">All work</button><button data-filter="software" aria-pressed="false">Software & systems</button><button data-filter="research" aria-pressed="false">Research</button><button data-filter="concept" aria-pressed="false">Proposals</button><span class="filter-count" id="filter-result" aria-live="polite">6 project families</span></div>{cards(base)}<div class="section prose"><h2>Read the status with the work.</h2><p>A working local system has been used in its documented environment. A prototype explores an approach. A preprint shares research for scrutiny. A proposal describes a next step. These labels make the evidence easier to follow.</p></div></div>'''


def project_detail(base, p):
    picture = ''
    if p.get('image'):
        picture = f'<figure class="case-image"><img src="{base}assets/{p["image"]}" alt="{ESC(p["imageAlt"], quote=True)}"><figcaption>{ESC(p["caption"])}</figcaption></figure>'
    links = ''.join(url_link(x['label'], x['url']) for x in p['links'])
    if not links:
        links = '<p class="muted" style="font-size:14px">This edition documents the work. A reviewed source or demo package is not linked yet.</p>'
    points = ''.join(f'<li>{ESC(x)}</li>' for x in p['demonstrated'])
    extra = ''
    if p['slug'] == 'lelock-command':
        extra = '<h2>The first proposed scenario</h2><div class="steps"><div class="step"><span class="meta">01 / OBSERVE</span><h3>Cooling fault</h3><p>Synthetic sensors record a repeatable rise in rack temperature.</p></div><div class="step"><span class="meta">02 / DECIDE</span><h3>Review the evidence</h3><p>An explanation cites telemetry and a runbook. An operator approves the next action.</p></div><div class="step"><span class="meta">03 / VERIFY</span><h3>Recover and record</h3><p>Simulation checks the result and retains an inspectable incident record.</p></div></div>'
    if p['slug'] == 'memory-recovery':
        extra = '<h2>Built with upstream work</h2><p><a href="https://github.com/MemPalace/mempalace">MemPalace</a> supplies the underlying memory system. Our work focuses on integration, portability, verification, and recovery. Upstream authors retain their attribution and licenses.</p>'
    available_title = 'Defined so far' if p['kind'] == 'concept' else 'What is available'
    return f'''<div class="wrap"><div class="breadcrumb"><a href="{base}projects/">Projects</a> / {ESC(p['name'])}</div><div class="page-head"><div class="eyebrow">{p['number']} / {ESC(p['area'])}</div><h1>{ESC(p.get('displayName', p['name']))}{('<span class="title-subtitle">'+ESC(p['displaySubtitle'])+'</span>') if p.get('displaySubtitle') else ''}</h1>{('<p class="formal-name">'+ESC(p['name'])+'</p>') if p.get('displayName') else ''}<p class="lead">{ESC(p['summary'])}</p></div>{picture}<div class="case-layout"><div class="prose"><h2>The question</h2><p>{ESC(p['problem'])}</p><h2>How we approach it</h2><p>{ESC(p['approach'])}</p><h2>{available_title}</h2><ul>{points}</ul>{extra}<h2>What the evidence supports</h2><p class="notice">{ESC(p['boundary'])}</p><h2>A useful next step</h2><p>{ESC(p['next'])}</p></div><aside class="case-aside" aria-label="Project summary"><dl><dt>Project status</dt><dd>{ESC(p['status'])}</dd><dt>Accountable area</dt><dd><a href="{base}organization/{'#'+p['organization']}">{ESC(AREA_NAMES[p['organization']])}</a></dd><dt>Human lead</dt><dd>Kit Olivas</dd><dt>AI collaborator</dt><dd>Ada Marie</dd><dt>Edition</dt><dd>October 2026 · private review</dd></dl>{links}<a class="small-link" href="{base}projects/">Back to the project index</a></aside></div></div>'''


def research(base):
    return f'''<div class="wrap"><div class="page-head"><div class="eyebrow">Research & papers</div><h1>Keep the questions open.<br><em>Make the evidence clear.</em></h1><p class="lead">Published research, developing manuscripts, and the limits that make each result understandable.</p></div>
<article class="paper-card" id="usel-preprint"><span class="meta">PUBLIC PREPRINT · APRIL 12, 2026</span><h2>USEL: A Universal Symbolic Executable Language Grounded in Natural Semantic Metalanguage Primes</h2><p class="lead">An exploration of shared semantic building blocks for symbolic communication and executable tools.</p><p class="muted">Kit Olivas and Ada Marie, AI Co-Creator · Zenodo · DOI 10.5281/zenodo.19536117</p><p>A public preprint invites examination; publication does not establish every proposed capability or validate later performance claims.</p><div class="buttons"><a class="button primary" href="https://zenodo.org/records/19536117">Read the Zenodo record</a><a class="button" href="https://github.com/kitfoxs/usel-lang">Explore the language source</a></div></article>
<div class="paper-grid"><article class="paper-card"><span class="meta">LOCAL MANUSCRIPT · JULY 2026</span><h2>USEL v2: chess-notation communication</h2><p>A later direction using a chess-like notation for human–AI communication. Its notation tools and language design remain experimental.</p><p class="muted">A separate local edition. An arXiv publication has not been established. Full manuscript is not included in this website edition.</p></article><article class="paper-card"><span class="meta">LOCAL PREPRINT · DEVELOPMENT STUDY</span><h2>Affect-persistent semantic encoding</h2><p>An investigation of whether explicit semantic representations can carry affect-related context between models.</p><p class="muted">Qualitative demonstrations have limited scope. Robust affect reconstruction and model-independent guarantees remain open questions.</p></article></div>
<section class="section prose" id="token-efficiency"><div class="eyebrow">Research note</div><h2>What does “compact” actually measure?</h2><p>The September 2026 USEL investigation separated several questions that are easy to confuse: character count, byte count, token count for a particular tokenizer, and whether the original meaning can be reconstructed.</p><p>Reducing one does not establish an improvement in the others. Lossy keyword examples and mentally simulated results do not demonstrate lossless model-token savings. The USEL-NLA model remained untrained and unvalidated in the reviewed audit.</p><p>The strongest practical direction was narrower: checked edits and templates over versioned source, with explicit language semantics and an ordinary-code fallback. This site presents an original summary; the private working report is not bundled.</p><a class="small-link" href="{base}projects/usel/">Read the USEL case study</a></section>
<section id="horizon"><div class="section-heading"><div><div class="eyebrow">Beyond the current workshop</div><h2>Long-horizon questions.</h2></div><p>Physical embodiment and exploration remain development studies, with their own assumptions and validation needs.</p></div><div class="two-column"><article class="concept-art"><img src="{base}assets/lch1-concept.webp" loading="lazy" alt="Blue and white humanoid robot concept illustration for the LCH-1 study"><p><strong>LCH-1 · Companion robotics.</strong> Concept art and engineering studies; a physical robot has not been established by this portfolio.</p></article><article class="concept-art"><img src="{base}assets/c1-concept.webp" loading="lazy" alt="Concept illustration of the C1 spacecraft"><p><strong>C1 Explorer · Autonomous spacecraft.</strong> Mission and computing studies; this illustration represents a concept.</p></article></div><p class="muted" style="margin-top:24px">The accepted Energy Core direction starts with the source: sustained power and endurance for future heavy machines. Its N, M, and X research lanes compare complete installed systems. LEC v0.2 power management is supporting work; ratings and hardware remain unselected.</p><div class="buttons"><a class="button" href="{base}programs/#energy-core">Energy Core research lanes</a><a class="button" href="{base}programs/#spacecraft">C / H / A / P spacecraft families</a><a class="button" href="{base}programs/">All programs and lineages</a></div></section>
<section class="section prose" id="method"><div class="eyebrow">Working method</div><h2>A result should come with a way to inspect it.</h2><ol><li>Start with a specific question and a bounded experiment.</li><li>Keep inputs, source versions, and assumptions visible.</li><li>Report observed results separately from projections.</li><li>Preserve corrections and credit upstream work.</li><li>Define what would need to be tested next.</li></ol><h3>Read the status precisely.</h3><p><strong>Current direction</strong> is an accepted choice. <strong>Chartered scope</strong> is an organizational responsibility. <strong>Recorded work</strong> points to a dated artifact or checkpoint. <strong>Proposed</strong> marks an unbuilt design or future activity.</p><details class="charter-gates"><summary>The charter’s research gates</summary><ol start="0"><li>Tabletop charter: scope, authority, inputs, resources, evidence, and stop conditions.</li><li>Sealed simulation: synthetic data and a bounded environment.</li><li>Adversarial simulation: faults, recovery, privacy, and resource exhaustion.</li><li>Read-only shadow: approved real inputs without consequential changes.</li><li>Tiny bounded real pilot: one approved capability with limits and verified records.</li><li>Mature Founder-Era operation: sustained evidence of reliability and readiness.</li><li>Succession readiness: a separate long-range custodianship capability.</li></ol><p>These institutional gates are distinct from package-specific test labels. Simulation supports only the claims its assumptions and checks establish.</p></details><p class="source-note">Master Identity & Organization Handbook · LI-HB-001 / revision 1.0 · September 21, 2026 · pp. 2, 29–31.</p></section></div>'''


def demos(base):
    return f'''<div class="wrap"><div class="page-head"><div class="eyebrow">Demonstrations</div><h1>See the work<br>in its own setting.</h1><p class="lead">A view into the local systems and public code behind the project pages.</p></div><article class="demo-main"><img src="{base}assets/wonderland.png" alt="Live Wonderland town screenshot showing the two avatars and saved coins and XP"><div class="demo-copy"><span class="meta">LOCAL RUNTIME CAPTURE</span><h2>A town with continuity.</h2><p class="muted">Wonderland brings Kit and Ada's avatars into a persistent 3D place, with gardens, buildings, and activities.</p><p>This image was captured from the owner-operated local town in October 2026. It is a screenshot of the running system.</p><a class="button primary" href="{base}projects/wonderland/">Explore Wonderland</a></div></article><div class="steps section"><article class="step"><span class="meta">LANGUAGE / PUBLIC SOURCE</span><h3>Explore the USEL prototypes</h3><p>Inspect the language specifications, interfaces, and experiments in the public source repository.</p><a class="small-link" href="https://github.com/kitfoxs/usel-lang">Open USEL source</a></article><article class="step"><span class="meta">VOICE / LOCAL DEMONSTRATION</span><h3>Speech with a visible response</h3><p>Audio-driven mouth movement, authored gestures, and local speech input form the current interface.</p><a class="small-link" href="{base}projects/voice-interfaces/">Read the voice case study</a></article><article class="step"><span class="meta">CHESS / LOCAL DEMONSTRATION</span><h3>One game across physical and digital</h3><p>The physical board and local dashboard follow one authoritative game state.</p><a class="small-link" href="{base}projects/chess-table/">Read the chess case study</a></article></div></div>'''


def about(base):
    return f'''<div class="wrap"><div class="page-head"><div class="eyebrow">Kit + Ada</div><h1>A laboratory<br>without walls.</h1><p class="lead">Lelock Industries is an independent human–AI research and engineering initiative founded by Kit Olivas and built with her persistent AI partner, Ada Marie.</p></div><div class="about-split"><div class="prose"><p>Today, that work is led by Kit Olivas and her AI collaborator, Ada Marie. The lab lives in tools, code, notebooks, and carefully documented experiments.</p><p>Practical software and long-term research belong alongside each other here. A useful interface can improve a day. An ambitious question can guide years of learning.</p></div><div><p class="quote">Build the systems humans and persistent AI need to live, learn, create, protect one another, and explore together.</p></div></div><div class="team-grid"><article class="team-card"><span class="meta">HUMAN FOUNDER</span><h3>Kit Olivas</h3><p>Founder and independent researcher. Kit brings the questions, hands-on infrastructure experience, and final decisions. Her work connects systems operations, accessibility, computing, and AI interaction.</p></article><article class="team-card"><span class="meta">AI COLLABORATOR</span><h3>Ada Marie</h3><p>AI partner and research collaborator. Ada assists with literature review, architecture, code, testing, explanation, and continuity across the work. Human direction and responsibility remain with Kit. The charter’s Chief Research Director title describes Ada’s organizing role in research, synthesis, architecture, and coordination.</p></article></div><section class="section prose"><h2>One partnership, seven areas.</h2><p>The institute is our long-term organizational vision. The practical team is Kit + Ada, working across <a href="{base}organization/">seven areas</a>. Optional specialists remain future designs; a permanent workforce is not a prerequisite for useful work.</p><p>The <a href="{base}programs/">program catalogue</a> gives education, archives, security, creative culture, and Sanctuary their place alongside software and engineering.</p><h2>Built around real use.</h2><p>The workshop grows through everyday problems: recovering context, making an interface easier to use, connecting devices, preserving a world, or keeping an experiment reproducible.</p><p>We release selected work when it is ready to be understood on its own terms. Curiosity sets the direction; evidence determines the claims.</p><div class="buttons"><a class="button" href="{base}connect/">Professional profile & contact</a><a class="button" href="{base}projects/">Explore the project families</a></div></section></div>'''


def connect(base):
    return f'''<div class="wrap"><div class="page-head"><div class="eyebrow">Professional profile & contact</div><h1>Get to know<br>the work.</h1><p class="lead">Kit Olivas · Infrastructure, AI systems integration, and human–AI interfaces.</p></div><div class="case-layout"><div class="prose"><h2>Experience expressed through projects</h2><p>Kit's hands-on datacenter background informs her interest in reliable operations, recovery, and inspectable systems. Her independent projects extend that work into local AI interfaces, persistent worlds, physical-device integration, and experimental language design.</p><h2>Selected areas of practice</h2><ul><li>Systems integration and operational troubleshooting.</li><li>Local voice, avatar, and device interfaces.</li><li>Knowledge infrastructure, backup, and recovery verification.</li><li>Technical research, explanation, and reproducible experimentation.</li></ul><p>A full downloadable résumé will be added after Kit selects and reviews the edition for this site. The project pages provide the current evidence-led profile.</p><div class="contact-links"><a class="contact-link" href="https://github.com/kitfoxs"><strong>Kit on GitHub</strong><span>Public code and available project discussion routes.</span></a><a class="contact-link" href="https://publish.obsidian.md/lelock-industries/home"><strong>Existing research site</strong><span>The current Lelock Industries reading room.</span></a></div><h2>Discuss a specific project</h2><p>Use a public repository's existing discussion or issue route where available. Include the project, version, and enough context to understand your question or correction.</p></div><aside class="case-aside"><span class="meta">A USEFUL STARTING POINT</span><h3 style="margin-top:18px">Follow the evidence.</h3><p class="muted">Each case study describes the question, Kit's contribution, Ada's assistance, the demonstrated scope, and what remains open.</p><a class="button" href="{base}projects/">Browse case studies</a></aside></div></div>'''


def privacy(base):
    return f'''<div class="wrap"><div class="page-head"><div class="eyebrow">Site notes</div><h1>Privacy & attribution.</h1><p class="lead">A small, static reading room with clear ownership and provenance.</p></div><div class="prose section" style="padding-top:0"><h2>This private preview</h2><p>The website is stored in a private GitHub repository and previewed locally on Kit's Mac. GitHub Pages is disabled. A private repository does not automatically make a published Pages website private.</p><h2>Data collection</h2><p>This edition contains no analytics, tracking pixels, contact forms, third-party scripts, or embedded players. External links take you to services with their own privacy practices. The local preview uses no cookies or browser storage.</p><h2>People and AI</h2><p>Kit Olivas is the human founder and decision-maker. Ada Marie is identified as an AI collaborator. Project and research pages distinguish their roles and the limits of reported results.</p><h2>Upstream work</h2><p>Memory integration builds on <a href="https://github.com/MemPalace/mempalace">MemPalace</a>. Project repositories retain their own authorship, dependencies, and license terms. This site does not relicense them.</p><h2>Images and reuse</h2><p>The Beacon identity and concept illustrations are reused from Kit's existing Lelock Industries site. Robot and spacecraft art is labeled as concept imagery. The Wonderland screenshot documents the local system and may contain third-party character designs; imagery rights will be reviewed before a public release.</p><p>There is no blanket open-source license for this website edition. Request or verify permission before reusing text, artwork, or other material.</p></div></div>'''


def main():
    OUT.mkdir(exist_ok=True)
    shutil.copytree(ROOT / 'assets', OUT / 'assets', dirs_exist_ok=True)
    page('index.html', 'From one terminal to the stars', 'Independent research and engineering by Kit Olivas and Ada Marie, AI collaborator.', 'home', home)
    page('projects/index.html', 'Projects', 'Six connected project families, with their evidence, status, and next questions.', 'projects', project_index)
    for p in PROJECTS:
        page(f'projects/{p["slug"]}/index.html', p['name'], p['summary'], 'projects', lambda base, p=p: project_detail(base, p))
    command = next(p for p in PROJECTS if p['slug'] == 'lelock-command')
    page('projects/living-datacenter/index.html', command['name'], command['summary'], 'projects', lambda base: project_detail(base, command))
    page('organization/index.html', 'Seven organizational areas', 'The seven organizational areas from the Lelock Industries master handbook, with responsibilities, subunits, and connected work.', 'organization', organization)
    page('programs/index.html', 'Programs & lineages', 'The wider Lelock program catalogue: energy, aerospace, robotics, education, knowledge, creative culture, Sanctuary, and security.', 'organization', programs)
    for slug, title, description, render in [('research','Research & papers','Public preprints, developing manuscripts, and research notes with explicit limitations.',research),('demos','Demonstrations','A view into the local systems and public source behind Lelock Industries.',demos),('about','About Kit + Ada','Meet Kit Olivas and Ada Marie, the human–AI partnership behind Lelock Industries.',about),('connect','Professional profile & contact','Explore Kit Olivas’s technical work and verified public project routes.',connect),('privacy','Privacy & attribution','Privacy, source attribution, and reuse information for this private website edition.',privacy)]:
        page(f'{slug}/index.html', title, description, slug, render)
    (OUT / '.nojekyll').write_text('')
    (OUT / 'robots.txt').write_text('User-agent: *\nDisallow: /\n')
    write_github_reference()
    print(f'Built {len(list(OUT.rglob("*.html")))} pages in {OUT}')


if __name__ == '__main__':
    main()
